name: Versioning and Publish

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Set the desired Node.js version

    - name: Install dependencies
      run: npm install  # Install dependencies in your package.json

    - name: Clean git working directory
      run: |
        git reset --hard  # Discard uncommitted changes
        git clean -fd  # Remove untracked files and directories

    - name: Set git user for commit
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"  # Set up the Git author

    - name: Automatically increment version (patch)
      run: |
        # Automatically increment the version (patch by default, change to 'minor' or 'major' as needed)
        npm version patch -m "Bump version to %s"  # This updates package.json and creates a new commit

    - name: Commit changes and push to GitHub
      run: |
        # Add all changes (including version bump) and commit them
        git add package.json package-lock.json  # Ensure package files are committed
        git commit -m "Automated version bump"
        git push origin main --tags  # Push the commit and new tag to GitHub
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}  # Use your GitHub token for authentication

    - name: Publish the new version to GitHub Packages
      run: |
        # Publish the updated version to GitHub Packages (or npm registry)
        npm publish --registry https://npm.pkg.github.com  # Change to npm registry if needed
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}  # Use your GitHub token for publishing
