name: Automated Commit and Push for package.json and package-lock.json

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  check_and_commit_push:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Check if package.json or package-lock.json have changes
      - name: Check for changes in package.json and package-lock.json
        id: changes_check
        run: |
          # Checking if there are changes in the specified files
          git diff --exit-code package.json package-lock.json || echo "Changes detected in package.json or package-lock.json"

      # Step 3: Commit changes if they exist
      - name: Commit changes if any
        if: steps.changes_check.outputs.exit_code != '0'  # If changes are detected
        run: |
          git config user.name "Automated Commit"
          git config user.email "action@github.com"
          git add package.json package-lock.json
          git commit -m "Automated update to package.json and package-lock.json"
        
      # Step 4: Push changes if commit was made
      - name: Push changes
        if: steps.changes_check.outputs.exit_code != '0'  # If commit was made
        run: |
          git push origin main

      # Step 5: Skip the commit and push if no changes were detected
      - name: Skip commit and push if no changes detected
        if: steps.changes_check.outputs.exit_code == '0'
        run: |
          echo "No changes detected in package.json or package-lock.json. No commit or push needed."
