jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Ensure git is clean
      run: |
        git add .
        git commit -m "Committing changes before versioning" || echo "No changes to commit"

    - name: Increment version (patch)
      run: |
        # Automatically increment the version (patch by default, change to 'minor' or 'major' as needed)
        npm version patch -m "Bump version to %s"  # This updates package.json and creates a new commit

    - name: Push version tag and changes to GitHub
      run: |
        # Push the commit and the new tag to GitHub
        git push origin main --tags
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}  # Authentication with GitHub Token

    - name: Publish the new version to GitHub Packages
      run: |
        # Publish the package to GitHub Packages
        npm publish --registry https://npm.pkg.github.com
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}  # Authentication for publishing
