jobs:
  version_bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Increment version
        run: |
          # Check if there are changes before bumping version
          git diff --exit-code
          npm version patch -m "Automated version bump to %s"

      - name: Commit changes if needed
        run: |
          # Check if there are changes before committing
          if [[ `git status --porcelain` ]]; then
            git add package.json package-lock.json
            git commit -m "Automated version bump"
            git push origin main
          else
            echo "No changes to commit."
          fi
