name: Automated Commit and Push for package.json and package-lock.json

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  check_and_commit_push:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Ensure npm is installed
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you want

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Ensure Git working directory is clean
      - name: Clean Git working directory
        run: |
          # Discard any local changes (optional: use with caution)
          git reset --hard
          git clean -fd

      # Step 5: Increment version (bump patch version)
      - name: Increment version
        run: |
          # Increment the patch version (1.0.0 -> 1.0.1)
          npm version patch -m "Automated version bump to %s"

      # Step 6: Commit changes (if version was bumped)
      - name: Commit version bump
        run: |
          git config user.name "Automated Commit"
          git config user.email "action@github.com"
          git add package.json package-lock.json
          git commit -m "Automated version bump"
        
      # Step 7: Push the commit to the repository
      - name: Push changes
        run: |
          git push origin main

      # Step 8: Skip commit and push if no changes were detected
      - name: Skip commit and push if no changes detected
        if: steps.changes_check.outputs.exit_code == '0'
        run: |
          echo "No changes detected. No commit or push needed."
