name: Versioning and Publish

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Clean git working directory
      run: |
        git reset --hard  # Discard uncommitted changes
        git clean -fd  # Remove untracked files and directories

    - name: Set git user for commit
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Check git status before version bump
      run: git status

    - name: Automatically increment version (patch)
      run: |
        npm version patch -m "Bump version to %s"
        git status  # Verify that there are changes to commit

    - name: Check git status after version bump
      run: git status

    - name: Commit changes and push to GitHub
      run: |
        git add package.json package-lock.json
        git commit -m "Automated version bump" || echo "No changes to commit"
        git push origin main --tags  # Push the commit and new tag to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication

    - name: Publish the new version to GitHub Packages
      run: |
        npm publish --registry https://npm.pkg.github.com  # Publish the package to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for publishing
