name: Versioning and Publish with LTS Failover

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
    # Optional: Trigger on other branches if needed
    tags:
      - 'v*'  # You can still trigger with version tags if you want

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Adjust this to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Increment version
      run: |
        # Auto-increment the version on every push. You can use patch, minor, or major
        npm version patch -m "Bump version to %s"  # You can change 'patch' to 'minor' or 'major' if needed

    - name: Push version tag and changes
      run: |
        # Push the changes and the new tag back to GitHub
        git push --follow-tags  # This pushes both the commit and the new version tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication

    - name: Publish new version to GitHub Packages
      run: |
        # Publish the new version to GitHub Packages
        npm publish --registry https://npm.pkg.github.com
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication

  failover-to-lts:
    runs-on: ubuntu-latest
    needs: versioning
    if: failure()  # This will run only if the versioning job fails
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Deploy LTS version
      run: |
        echo "Deployment failed, rolling back to LTS version"
        npm install @your-org/your-lts-version  # Rollback to the LTS version
        npm publish --registry https://npm.pkg.github.com
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

