name: Auto Version Bump and LTS Support

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger if needed

jobs:
  version_bump:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (adjust to your preferred version)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Set Git user identity (required for committing)
      - name: Set Git user identity
        run: |
          git config --global user.name "Automated Commit"
          git config --global user.email "action@github.com"

      # Step 5: Clean git working directory and remove node_modules changes
      - name: Clean git working directory and node_modules changes
        run: |
          git reset --hard
          git clean -fd
          git status
          # Ensure node_modules are not tracked or modified
          git rm -r --cached node_modules || echo "No node_modules to remove"
          echo "Removed node_modules changes from git."

      # Step 6: Run Version Bump
      - name: Run version bump
        id: version_bump
        run: |
          echo "Commit message: $GITHUB_EVENT_HEAD_COMMIT_MESSAGE"
          if [[ "${GITHUB_EVENT_HEAD_COMMIT_MESSAGE}" == *"lts"* ]]; then
            echo "LTS flag detected. Bumping LTS version."
            npm version patch --preid "lts" -m "Automated version bump to %s (LTS)"
          else
            echo "Bumping regular version."
            npm version patch -m "Automated version bump to %s"
          fi

      # Step 7: Run npm install to update package-lock.json
      - name: Run npm install to update package-lock.json
        run: npm install

      # Step 8: Check for changes to commit (Exclude node_modules)
      - name: Check for changes to commit (package.json, package-lock.json)
        run: |
          git status --porcelain | grep -E 'package.json|package-lock.json' || echo "No relevant changes detected."

      # Step 9: Commit version bump changes if needed
      - name: Commit changes if there are updates
        run: |
          if [[ $(git status --porcelain | grep -E 'package.json|package-lock.json') ]]; then
            echo "Committing version bump changes."
            git add package.json package-lock.json
            git commit -m "Automated version bump"
            git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
          else
            echo "No changes detected in package.json or package-lock.json, skipping commit and push."
          fi

      # Step 10: Handle errors and ensure LTS version if needed
      - name: Handle errors and ensure LTS version (if failure)
        if: failure()
        run: |
          echo "Error detected, applying latest LTS version."
          npm version patch --preid "lts" -m "Automated version bump to latest LTS"
          git add package.json package-lock.json
          git commit -m "Automated LTS version bump"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
