name: Versioning and Branch Creation

on:
  push:
    branches:
      - main  # Trigger this workflow when changes are pushed to the `main` branch
  pull_request:
    branches:
      - main  # Trigger this workflow on pull requests targeting the `main` branch

jobs:
  versioning:
    runs-on: ubuntu-latest  # This can be changed to `windows-latest` or `macos-latest` if needed

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Retrieve current version from version.txt
      id: version
      run: |
        VERSION_FILE="version.txt"
        if [ -f "$VERSION_FILE" ]; then
          VERSION=$(cat $VERSION_FILE)
        else
          VERSION="1.0.0"  # If version.txt doesn't exist, start with this version
        fi
        echo "Current Version: $VERSION"
        # Increment the patch version
        IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"
        PATCH_VERSION=$((VERSION_PARTS[2] + 1))
        NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH_VERSION"
        echo "New Version: $NEW_VERSION"
        echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Update version.txt with new version
      run: |
        echo ${{ env.VERSION }} > version.txt
        cat version.txt

    - name: Commit version.txt changes
      run: |
        git config --global user.email "vamsimohanyacham@gmail.com"  # Replace with your email
        git config --global user.name "vamsimohanyacham"  # Replace with your GitHub username
        git add version.txt
        git commit -m "Update version to ${{ env.VERSION }}"
        git push origin main

    - name: Create a new feature branch
      run: |
        BRANCH_NAME="feature/version-${{ env.VERSION }}"
        git checkout -b $BRANCH_NAME
        git push origin $BRANCH_NAME

    - name: Create a Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Update version to ${{ env.VERSION }}"
        body: "This PR updates the version in version.txt"
        base: main
        head: feature/version-${{ env.VERSION }}
