name: Version and Deploy

on:
  push:
    branches:
      - main  # Triggers only on commits to the 'main' branch (or change it to your default branch)

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Node.js (if your project uses Node)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Choose the Node.js version according to your project

    # Step 3: Configure git (for committing changes automatically)
    - name: Configure git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    # Step 4: Bump the version using npm or your chosen versioning method
    - name: Bump version
      run: |
        npm version patch -m "Bump version to %s"
        # For other versioning tools, use their respective commands
        # Example for Python: python setup.py versioning

    # Step 5: Commit and push version update
    - name: Commit and push new version
      run: |
        git add package.json # or relevant files for versioning
        git commit -m "Bumped version"
        git push origin main  # or your branch name

    # Step 6: Optionally, publish your package (e.g., to npm, Docker, etc.)
    # - name: Publish to npm
    #   run: npm publish --access public

