name: Versioning and Publish with LTS Failover

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Adjust this to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Increment version
      run: |
        # Increment version using npm version (patch, minor, major) 
        npm version patch -m "Bump version to %s"  # Change 'patch' to 'minor' or 'major' if needed

    - name: Push version tag and changes
      run: |
        # Push both the commit and the new tag to GitHub
        git push --follow-tags origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication

    - name: Publish new version to GitHub Packages
      run: |
        # Publish the new version to GitHub Packages
        npm publish --registry https://npm.pkg.github.com
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication

  failover-to-lts:
    runs-on: ubuntu-latest
    needs: versioning
    if: failure()  # This will run only if the versioning job fails
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Deploy LTS version
      run: |
        echo "Deployment failed, rolling back to LTS version"
        npm install @your-org/your-lts-version  # Rollback to the LTS version
        npm publish --registry https://npm.pkg.github.com
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
