      # Step 5: Clean git working directory and remove node_modules changes
      - name: Clean git working directory and node_modules changes
        run: |
          git reset --hard
          git clean -fd
          echo "Removed changes in node_modules."

      # Step 6: Run Version Bump
      - name: Run version bump
        id: version_bump
        run: |
          echo "Commit message: $GITHUB_EVENT_HEAD_COMMIT_MESSAGE"
          if [[ "${GITHUB_EVENT_HEAD_COMMIT_MESSAGE}" == *"lts"* ]]; then
            echo "LTS flag detected. Bumping LTS version."
            npm version patch --preid "lts" -m "Automated version bump to %s (LTS)"
          else
            echo "Bumping regular version."
            npm version patch -m "Automated version bump to %s"
          fi

      # Step 7: Run npm install to update package-lock.json
      - name: Run npm install to update package-lock.json
        run: npm install

      # Step 8: Check for changes to commit and exclude node_modules
      - name: Check for changes to commit
        run: |
          git status --porcelain | grep -v 'node_modules' || echo "Changes detected in package.json or package-lock.json"
